# Generated by Django 5.0.6 on 2024-06-25 22:32

import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='name')),
                ('phone_number', models.CharField(max_length=16, validators=[common.validators.validate_phone_number], verbose_name='phone number')),
                ('email', models.EmailField(max_length=64, verbose_name='email address')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='company')),
                ('position', models.CharField(blank=True, max_length=64, null=True, verbose_name='position')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('notes', models.CharField(blank=True, max_length=128, null=True, verbose_name='notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
