# Generated by Django 5.0.6 on 2024-06-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('id',)},
        ),
    ]
